apiVersion: v1
entries:
  descheduler:
  - apiVersion: v1
    appVersion: v0.5.0-4-ga7ceb671
    created: 2018-05-05T12:33:09.140170587+02:00
    description: A Helm chart for Kubernetes Descheduler
    digest: 560d2d878427bc586db0d9b2a46f1f99ea5ef5bf7ef1ab36294fdd03bc19c0d6
    name: descheduler
    urls:
    - descheduler-0.1.0.tgz
    version: 0.1.0
  efk:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-05-05T12:33:09.141295169+02:00
    description: A Helm chart for EFK stack
    digest: cdf1952479fb190fa332479a07ba65ee413cbdf23c411a792956a0e7725d6ff4
    name: efk
    urls:
    - efk-0.1.0.tgz
    version: 0.1.0
  elasticsearch:
  - apiVersion: v1
    appVersion: 6.1.3
    created: 2018-05-05T12:33:09.141809643+02:00
    description: A Helm chart for Elasticsearch cluster
    digest: eb8163d9a2153c5760e80b530a4ff8653c569b24a3cffd26a1f1be8a4e080179
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v1
    appVersion: 6.1.3
    created: 2018-05-05T12:33:09.141551479+02:00
    description: A Helm chart for Elasticsearch cluster
    digest: 32a25b05c73cc92b49fc53b64d25cee44d28e1062db1ef12f2cbcb0e260d0019
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-0.1.3.tgz
    version: 0.1.3
  elasticsearch-operator:
  - apiVersion: v1
    appVersion: 0.0.12
    created: 2018-05-05T12:33:09.142640689+02:00
    description: A Helm chart for Elasticsearch operator
    digest: 5b946ae9c69685e80964599cadfcf1b675b124eb393471ee0f335e63eb572024
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch-operator
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-operator-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v1
    appVersion: 0.0.12
    created: 2018-05-05T12:33:09.142371552+02:00
    description: A Helm chart for Elasticsearch operator
    digest: f909a7a19ec3e04259a40728c7428515701aed1f8cae7407c8b6a993b6e083d8
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch-operator
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-operator-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v1
    appVersion: 0.0.10
    created: 2018-05-05T12:33:09.142100637+02:00
    description: A Helm chart for Elasticsearch operator
    digest: dea5f18a301f11dee2aef9ac1dd3b44069e4bc128c8c32f8e1322a55a385a282
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch-operator
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-operator-0.1.3.tgz
    version: 0.1.3
  kibana:
  - appVersion: 6.1.3
    created: 2018-05-05T12:33:09.143029587+02:00
    description: Kibana is an open source data visualization plugin for Elasticsearch
    digest: 17482b8ec6895ab271666a834223554857490c36acc449e87b2ba4b134b3e704
    engine: gotpl
    home: https://www.elastic.co/products/kibana
    icon: https://raw.githubusercontent.com/elastic/kibana/master/src/ui/public/icons/kibana-color.svg
    keywords:
    - elasticsearch
    - kibana
    maintainers:
    - email: casey@monax.io
      name: compleatang
    - email: alen.komljen@live.com
      name: komljen
    name: kibana
    sources:
    - https://github.com/elastic/kibana
    urls:
    - kibana-0.4.2.tgz
    version: 0.4.2
generated: 2018-05-05T12:33:09.139691635+02:00
